name: rollplay_html
description: Front-end web-app that makes use of Roll-API
version: 0.0.1
homepage: https://the.lastgimbus.com/rollplay

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  rollapi:
    git:
      url: https://github.com/TheLastGimbus/rollapi_dart/
      ref: dev

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  lints: ^2.1.1
