name: rollplay_html
description: Front-end web-app that makes use of Roll-API
version: 0.0.1
homepage: https://the.lastgimbus.com/rollplay

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  rollapi:
    git:
      url: https://github.com/TheLastGimbus/rollapi_dart/
      ref: dev

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
